version: "3.9"

services:
  dev:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    # Modify image name based on your needs
    image: nvcr.io/nvidia/pytorch:23.06-py3
    ipc: host
    ports:
      - 8888:8888
    # Modify this to host, default, etc to suit your needs
    network_mode: host
    # Uncomment this if you need to reuse container everytime
    # restart: always
    # Uncomment and modify this if you need to configure proxy
    # environment:
    #   - http_proxy=http://127.0.0.1:7890
    #   - https_proxy=http://127.0.0.1:7890
    #   - all_proxy=socks5://127.0.0.1:7891
    stdin_open: true
    tty: true
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      nproc:
        soft: 65535
        hard: 65535
    volumes:
      - '$PWD:/workspace'
