FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -y && apt install -y curl software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update -y && apt install -y python3.9 python3.9-distutils
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.9 get-pip.py
RUN pip3 install fschat
RUN pip3 install fschat[model_worker,webui] pydantic==1.10.13

COPY requirements.txt ./
RUN pip install -r /requirements.txt

EXPOSE 8000
EXPOSE 21001